extends: ["spectral:oas"]
rules:
  # أوقف/خفّف قواعد قد تفشل مع مواصفات بذرة فارغة
  openapi-tags: off
  operation-tags: off
  operation-operationId-unique: off
  oas3-api-servers: off
  oas3-unused-components-schema: off
  no-server-example.com: off
  info-contact: warn
  oas3-schema: warn
  oas3-valid-schema-example: warn
