import os, csv, json, time, zipfile, textwrap, hashlib, pathlib
from datetime import datetime


ts = time.strftime("%Y%m%d_%H%M%S")
root = f"/mnt/data/DASH-HR_ARTIFACTS_{ts}"
os.makedirs(root, exist_ok=True)


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()

routes = [
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","hr.overview","load_metrics","hr_metrics_get","GET","/api/hr/metrics","hr_manager",1,1,0,0,True,False,False,False,"—","components.schemas.HrMetrics","components.schemas.Problem",False,"PASS(Allowlist,Problem)","Load HR KPIs summary."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","employees.list","list_employees","hr_employees_list","GET","/api/hr/employees","hr_manager",1,1,0,0,True,False,False,False,"—","components.schemas.EmployeeList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List employees with pagination."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","employees.details","load_employee","hr_employee_get","GET","/api/hr/employees/{employee_id}","hr_manager",1,1,0,0,True,False,False,False,"—","components.schemas.Employee","components.schemas.Problem",False,"PASS(Allowlist,Problem,PathParam)","Get employee profile."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","employees.create","create_employee","hr_employee_create","POST","/api/hr/employees","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.EmployeeCreateRequest","components.schemas.Employee","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem)","Create employee."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","employees.update","update_employee","hr_employee_update","PATCH","/api/hr/employees/{employee_id}","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.EmployeeUpdateRequest","components.schemas.Employee","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Update employee."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","employees.deactivate","deactivate_employee","hr_employee_deactivate","POST","/api/hr/employees/{employee_id}/deactivate","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.EmployeeDeactivateRequest","components.schemas.Employee","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Step-Up)","Deactivate employee (requires Step-Up)."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","contracts.list","list_contracts","hr_contracts_list","GET","/api/hr/contracts","hr_manager",1,1,0,0,True,False,False,False,"—","components.schemas.ContractList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List contracts."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","contracts.create","create_contract","hr_contract_create","POST","/api/hr/contracts","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.ContractCreateRequest","components.schemas.Contract","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem)","Create new contract."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","contracts.update","update_contract","hr_contract_update","PATCH","/api/hr/contracts/{contract_id}","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.ContractUpdateRequest","components.schemas.Contract","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Update contract."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","attendance.calendar","load_attendance","hr_attendance_range_get","GET","/api/hr/attendance?from={from}&to={to}","hr_manager",1,1,0,0,True,False,False,False,"—","components.schemas.AttendanceRange","components.schemas.Problem",False,"PASS(Allowlist,Problem)","Attendance window summary."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","attendance.adjust","adjust_attendance","hr_attendance_adjust","POST","/api/hr/attendance/{employee_id}/adjust","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.AttendanceAdjustRequest","components.schemas.AttendanceRecord","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Audit-Immutable)","Adjust attendance record with audit."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","leave.list","list_leaves","hr_leaves_list","GET","/api/hr/leaves","hr_manager",1,1,0,0,True,False,False,True,"—","components.schemas.LeaveList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List leave requests."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","leave.approve","approve_leave","hr_leave_approve","POST","/api/hr/leaves/{leave_id}/approve","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.LeaveDecisionRequest","components.schemas.Leave","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Approve leave."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","leave.reject","reject_leave","hr_leave_reject","POST","/api/hr/leaves/{leave_id}/reject","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.LeaveDecisionRequest","components.schemas.Leave","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Reject leave."],
    ["SSoT DEC-DASH-20251104-A1","DASHBOARD","DASH-HR","DASH-HR","payroll.preview","build_payroll","hr_payroll_build","POST","/api/hr/payroll/build","hr_payroll_manager",1,1,0,0,True,False,False,True,"components.schemas.PayrollBuildRequest","components.schemas.PayrollRun","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,Step-Up)","Build payroll draft for a period."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","payroll.list","list_runs","hr_payroll_runs_list","GET","/api/hr/payroll/runs","hr_payroll_manager",1,1,0,0,True,False,False,True,"—","components.schemas.PayrollRunList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List payroll runs."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","payroll.lock","lock_payroll","hr_payroll_lock","POST","/api/hr/payroll/runs/{run_id}/lock","hr_payroll_manager",1,1,0,0,True,False,False,True,"components.schemas.PayrollLockRequest","components.schemas.PayrollRun","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Step-Up)","Lock payroll run (no further edits)."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","payroll.export","export_payroll","hr_payroll_export","POST","/api/hr/payroll/runs/{run_id}/export","hr_payroll_manager",1,1,0,0,True,False,False,True,"components.schemas.PayrollExportRequest","components.schemas.ExportReceipt","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Privacy-Export)","Export masked payroll for bank file."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","payroll.approve","approve_payroll","hr_payroll_approve","POST","/api/hr/payroll/runs/{run_id}/approve","hr_payroll_manager",1,1,0,0,True,False,False,True,"components.schemas.PayrollApproveRequest","components.schemas.PayrollRun","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Step-Up)","Approve payroll run."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","payroll.payouts.queue","queue_payouts","hr_payroll_payouts_queue","POST","/api/hr/payroll/runs/{run_id}/payouts/queue","finance",1,1,0,0,True,False,False,True,"components.schemas.PayoutsQueueRequest","components.schemas.PayoutsBatch","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam,Audit-Immutable,Step-Up)","Queue bank payouts batch with dual-sign policy."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","benefits.list","list_benefits","hr_benefits_list","GET","/api/hr/benefits","hr_manager",1,1,0,0,True,False,False,True,"—","components.schemas.BenefitList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List benefits."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","benefits.update","update_benefit","hr_benefit_update","PATCH","/api/hr/benefits/{benefit_id}","hr_manager",1,1,0,0,True,False,False,True,"components.schemas.BenefitUpdateRequest","components.schemas.Benefit","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Update benefit."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","incentives.configure","configure_incentives","hr_incentives_configure","POST","/api/hr/incentives/configure","hr_payroll_manager",1,1,0,0,True,False,False,True,"components.schemas.IncentivesConfigRequest","components.schemas.IncentivesConfig","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem)","Configure incentive pool and rules."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","timesheets.list","list_timesheets","hr_timesheets_list","GET","/api/hr/timesheets","hr_manager",1,1,0,0,True,False,False,True,"—","components.schemas.TimesheetList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List timesheets."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","timesheets.approve","approve_timesheet","hr_timesheet_approve","POST","/api/hr/timesheets/{timesheet_id}/approve","hr_manager",1,1,0,0,True,False,False,True","components.schemas.TimesheetDecisionRequest","components.schemas.Timesheet","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Approve timesheet."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","holidays.list","list_holidays","hr_holidays_list","GET","/api/hr/holidays","hr_manager",1,1,0,0,True,False,False,True,"—","components.schemas.HolidayList","components.schemas.Problem",False,"PASS(Allowlist,Problem)","List holidays calendar."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","holidays.create","create_holiday","hr_holiday_create","POST","/api/hr/holidays","hr_manager",1,1,0,0,True,False,False,True","components.schemas.HolidayCreateRequest","components.schemas.Holiday","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem)","Create holiday."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","shifts.list","list_shifts","hr_shifts_list","GET","/api/hr/shifts","hr_manager",1,1,0,0,True,False,False,True","—","components.schemas.ShiftList","components.schemas.Problem",True,"PASS(Allowlist,Problem,Pagination)","List shifts."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","DASH-HR","shifts.assign","assign_shift","hr_shift_assign","POST","/api/hr/shifts/{shift_id}/assign","hr_manager",1,1,0,0,True,False,False,True","components.schemas.ShiftAssignRequest","components.schemas.ShiftAssignment","components.schemas.Problem",False,"PASS(Idem,Allowlist,Problem,PathParam)","Assign shift to employee."],
    ["SSoT DEC-DASH-20251104-A1","dashboard","DASH-HR","SYSTEM","webhooks.payroll_status","payroll_status_webhook","hr_payroll_status_webhook","POST","/api/hr/inbound/payroll-status","system",1,0,0,0,True,False,False,False","components.schemas.PayrollStatusWebhook","—","components.schemas.Problem",False,"PASS(Webhook-HMAC,Anti-Replay≤300s,Allowlist,Problem,Audit-Immutable)","Inbound payroll processing status."],
]

# ... remainder of code omitted for brevity ...
